README.md		/usr/share/arduino/hardware/hardkernel/odroid/
platform.txt		/usr/share/arduino/hardware/hardkernel/odroid/
programmers.txt		/usr/share/arduino/hardware/hardkernel/odroid/
cores			/usr/share/arduino/hardware/hardkernel/odroid/
libraries		/usr/share/arduino/hardware/hardkernel/odroid/
tools			/usr/share/arduino/hardware/hardkernel/odroid/
image			/usr/share/arduino/hardware/hardkernel/odroid/
